CREATE TABLE bt_stats (
    Symbol VARCHAR(255) PRIMARY KEY,
    Start DATE,
    Ended DATE,
    Duration INTERVAL,
    Exposure_Time DECIMAL(18, 2),
    Equity_Final DECIMAL(18, 2),
    Equity_Peak DECIMAL(18, 2),
    Return DECIMAL(18, 6),
    Buy_Hold_Return DECIMAL(18, 6),
    Return_annual DECIMAL(18, 6),
    Volatility_annual DECIMAL(18, 6),
    Sharpe_Ratio DECIMAL(18, 6),
    Sortino_Ratio DECIMAL(18, 6),
    Calmar_Ratio DECIMAL(18, 6),
    Max_Drawdown DECIMAL(18, 6),
    Avg_Drawdown DECIMAL(18, 6),
    Max_Drawdown_Duration INTERVAL,
    Avg_Drawdown_Duration INTERVAL,
    Num_Trades INTEGER,
    Win_Rate DECIMAL(18, 2),
    Best_Trade DECIMAL(18, 6),
    Worst_Trade DECIMAL(18, 6),
    Avg_Trade DECIMAL(18, 6),
    Max_Trade_Duration INTERVAL,
    Avg_Trade_Duration INTERVAL,
    Profit_Factor DECIMAL(18, 6),
    Expectancy DECIMAL(18, 6),
    SQN DECIMAL(18, 6),
    _strategy TEXT,
    _equity_curve TEXT,
    _trades TEXT
);
